onerror {resume}
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_info[66:0]} swinfo_ch0
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_info[133:67]} sw_info_ch1
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_info[42:0]} wdata_ch0
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_info[85:43]} wdata_ch1
quietly WaveActivateNextPane {} 0
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/clk_sys
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/rst_n
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/swinfo_ch0
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_valid[0]}
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_ready[0]}
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/sw_info_ch1
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_valid[1]}
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_ready[1]}
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/luser
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/cuser
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/addr_info
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/addr_valid
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/addr_ready
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/wdata_ch0
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_valid[0]}
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_ready[0]}
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/wdata_ch1
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_valid[1]}
add wave -noupdate {/axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_wdata_ready[1]}
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/wdata_info
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/wdata_valid
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/wdata_ready
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2254668 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 185
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {4614426 ps}
