onerror {resume}
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/s_wdata_info[42:0]} u0
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/s_wdata_info[85:43]} u1
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split/addr_info[36:5]} addr
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split/m_wdata_info[171:129]} wdata
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split/m_wdata_info[42:0]} wdata3
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split/m_addr_info[66:0]} waddr3
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_mreq_split/m_addr_info[267:201]} waddr1
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_info[66:0]} waddr0
quietly virtual signal -install /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit { /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sreq_arbit/s_addr_info[133:67]} waddr1
quietly WaveActivateNextPane {} 0
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/clk_sys
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/rst_n
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/resp_info
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/resp_valid
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/resp_ready
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/m_resp_info
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/m_resp_ready
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/m_resp_valid
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/fifo_full
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/fifo_rden_temp
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/fifo_rddata
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/fifo_empty
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/cuser
add wave -noupdate /axi_interconnect_tb/u0_axi_interconnect_crossbar/u0_axi_interconnect_crossbar_switch/u_axi_interconnect_crossbar_sresp_split/fifo_rden
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1108344 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {979672 ps} {1444830 ps}
